#!/usr/bin/env bash
# tools/pin-versions.sh — resolve the newest release of every pinned tool and
# print versions.conf (URL + SHA-256 per artifact). Maintenance workflow:
#
#   tools/pin-versions.sh > versions.conf.new && diff versions.conf versions.conf.new
#
# then review, move it over versions.conf, test, commit. `setup.sh update` runs
# it too, to show what is newer. Needs curl, jq-free
# python3 and an authenticated `gh` (GitHub API rate limits).
set -euo pipefail

say() { printf '%s\n' "$*"; }
# --check: newest versions only (no downloads, no GitHub API), for `update`.
# --only KEY...: just these entries, for recording a chosen update.
CHECK=0 ONLY=""
while (( $# )); do
  case "$1" in
    --check) CHECK=1 ;;
    --only) shift; ONLY=" $* "; break ;;
    *) printf 'usage: %s [--check] [--only KEY...]\n' "$0" >&2; exit 2 ;;
  esac
  shift
done
want() { [[ -z "$ONLY" || "$ONLY" == *" $1 "* ]]; }
# latest_tag REPO — the newest release's tag, from GitHub's redirect (no API).
latest_tag() {
  curl -fsSI -o /dev/null -w '%{redirect_url}' "https://github.com/$1/releases/latest" | sed -E 's#.*/tag/##'
}
# GitHub API: through gh when it is signed in (5000 requests an hour), else
# anonymously (60 an hour, enough for one run).
if gh auth status >/dev/null 2>&1; then api() { gh api "$1"; }
else api() { curl -fsSL -H 'Accept: application/vnd.github+json' "https://api.github.com/$1"; }; fi
err() { printf 'pin: %s\n' "$*" >&2; }

# GitHub release asset: KEY REPO ASSET_REGEX [TAG]
# SHA-256 is GitHub's own digest of the uploaded asset; where the project
# publishes a checksum file it must agree (checked by the installer too).
PICK_ASSET='
import json, re, sys
rel = json.load(sys.stdin)
rx = re.compile(sys.argv[1])
hits = [a for a in rel["assets"] if rx.search(a["name"])]
if len(hits) != 1:
    sys.exit("%d assets match %r in %s: %s" % (len(hits), sys.argv[1], rel.get("tag_name"), [x.get("name") for x in hits]))
a = hits[0]
d = a.get("digest") or ""
print(rel["tag_name"], a["browser_download_url"], d.split(":", 1)[1] if d.startswith("sha256:") else "")
'
gh_asset() {
  local key="$1" repo="$2" regex="$3" tag="${4:-}" json line
  want "$key" || return 0
  if (( CHECK )); then
    [[ -n "$tag" ]] || tag="$(latest_tag "$repo")"
    [[ -n "$tag" ]] || { err "$key: no release found for $repo"; exit 1; }
    tag="${tag#rust-}"; say "${key}_VERSION=\"${tag#v}\""
    return 0
  fi
  if [[ -n "$tag" ]]; then json="$(api "repos/$repo/releases/tags/$tag")"
  else json="$(api "repos/$repo/releases/latest")"; fi
  line="$(python3 -c "$PICK_ASSET" "$regex" <<<"$json" 2>&1)" || { err "$key: $line"; exit 1; }
  read -r tag url sha <<<"$line"
  if [[ -z "$sha" ]]; then   # old assets carry no digest: hash the download
    sha="$(curl -fsSL "$url" | sha256sum | cut -d' ' -f1)"
  fi
  tag="${tag#rust-}"; say "${key}_VERSION=\"${tag#v}\""
  say "${key}_URL=\"$url\""
  say "${key}_SHA256=\"$sha\""
  say ""
}

# Any URL: KEY VERSION URL [SHA256] — hashes the download when no SHA given.
url_pin() {
  local key="$1" ver="$2" url="$3" sha="${4:-}"
  want "$key" || return 0
  (( CHECK )) && { say "${key}_VERSION=\"$ver\""; return 0; }
  [[ -n "$sha" ]] || sha="$(curl -fsSL "$url" | sha256sum | cut -d' ' -f1)"
  say "${key}_VERSION=\"$ver\""
  say "${key}_URL=\"$url\""
  say "${key}_SHA256=\"$sha\""
  say ""
}

# GNOME extension: KEY UUID — its newest release for GNOME 50 on
# extensions.gnome.org.
ego_pin() {
  local key="$1" uuid="$2" pk="" v=""
  want "$key" || return 0
  read -r pk v < <(curl -fsSL "https://extensions.gnome.org/extension-info/?uuid=$uuid&shell_version=50" \
    | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d["version_tag"], d.get("version_name") or d["version"])') || true
  [[ -n "$pk" ]] || { err "$key: $uuid not found for GNOME 50"; exit 1; }
  url_pin "$key" "$v" "https://extensions.gnome.org/download-extension/$uuid.shell-extension.zip?version_tag=$pk"
}

cat <<'HEAD'
# Pinned upstream artifacts — generated by tools/pin-versions.sh, then reviewed.
# Every download is checked against its SHA-256 before it is installed.
# Update: tools/pin-versions.sh > versions.conf.new, review the diff, test.

HEAD

say "# ---- A. Terminal and shell"
gh_asset KITTY kovidgoyal/kitty '^kitty-[0-9.]+-x86_64\.txz$'
say "# Ghostty has no official Linux build: the Ubuntu .deb that ghostty.org lists"
say "# (community-built, github.com/mkasberg/ghostty-ubuntu); version = upstream part."
gh_asset GHOSTTY mkasberg/ghostty-ubuntu '^ghostty_[0-9.]+-0\.ppa[0-9]+_amd64_26\.04\.deb$' \
  | sed -E 's/^(GHOSTTY_VERSION="[0-9.]+)-[^"]*"/\1"/'
gh_asset PWSH PowerShell/PowerShell '^powershell-[0-9.]+-linux-x64\.tar\.gz$'
gh_asset STARSHIP starship/starship '^starship-x86_64-unknown-linux-gnu\.tar\.gz$'
gh_asset ZOXIDE ajeetdsouza/zoxide '^zoxide-[0-9.]+-x86_64-unknown-linux-musl\.tar\.gz$'
gh_asset CASCADIA microsoft/cascadia-code '^CascadiaCode-[0-9.]+\.zip$'
for f in CascadiaCode CascadiaMono FiraCode JetBrainsMono; do
  gh_asset "NERDFONT_$(tr '[:lower:]' '[:upper:]' <<<"$f")" ryanoasis/nerd-fonts "^${f}\.tar\.xz\$"
done
ego_pin QUAKE_TERMINAL quake-terminal@diegodario88.github.io
ego_pin CLIPBOARD_INDICATOR clipboard-indicator@tudmotu.com

say "# ---- B. Editors and IDEs"
gh_asset NEOVIM neovim/neovim '^nvim-linux-x86_64\.tar\.gz$'
if want JETBRAINS_TOOLBOX; then
tb="$(curl -fsSL 'https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release')"
read -r tb_ver tb_url tb_sumurl < <(python3 -c 'import json,sys; r=json.load(sys.stdin)["TBA"][0]; l=r["downloads"]["linux"]; print(r["version"], l["link"], l["checksumLink"])' <<<"$tb")
url_pin JETBRAINS_TOOLBOX "$tb_ver" "$tb_url" "$(curl -fsSL "$tb_sumurl" | cut -d' ' -f1)"
fi
if want BCOMPARE; then
bc="$(curl -fsSL 'https://www.scootersoftware.com/checkupdates.php?product=bc5&minor=0&maint=0&build=1&platform=linux&edition=pro&lang=silent')"
bc_ver="$(grep -oE 'latestversion="[^"]+' <<<"$bc" | cut -d'"' -f2 | sed 's/ build /./')"
bc_build="$(grep -oE 'latestbuild="[0-9]+' <<<"$bc" | cut -d'"' -f2)"
url_pin BCOMPARE "$bc_ver" "https://www.scootersoftware.com/files/bcompare-${bc_ver%.*}.${bc_build}_amd64.deb"
fi

say "# Antigravity IDE 2.x: Google ships it for Linux as a tarball only (its apt"
say "# repository stays on the old 1.x line); newest one from the download page."
if want ANTIGRAVITY; then
  ag_url="$(curl -fsSL --compressed https://antigravity.google/download \
    | grep -oE 'https://[^"'"'"' <>]*/stable/[0-9.]+-[0-9]+/linux-x64/Antigravity%20IDE\.tar\.gz' | head -1)"
  [[ -n "$ag_url" ]] || { err "ANTIGRAVITY: no Linux tarball on antigravity.google/download"; exit 1; }
  url_pin ANTIGRAVITY "$(sed -E 's#.*/stable/([0-9.]+)-[0-9]+/.*#\1#' <<<"$ag_url")" "$ag_url"
fi
say "# Antigravity 2.0 (the agent manager): a tarball as well, from the same page."
if want ANTIGRAVITY_HUB; then
  hub_url="$(curl -fsSL --compressed https://antigravity.google/download \
    | grep -oE 'https://[^"'"'"' <>]*/antigravity-hub/[0-9.]+-[0-9]+/linux-x64/Antigravity\.tar\.gz' | head -1)"
  [[ -n "$hub_url" ]] || { err "ANTIGRAVITY_HUB: no Linux tarball on antigravity.google/download"; exit 1; }
  url_pin ANTIGRAVITY_HUB "$(sed -E 's#.*/antigravity-hub/([0-9.]+)-[0-9]+/.*#\1#' <<<"$hub_url")" "$hub_url"
fi

say "# ---- C. AI coding agents (Claude Code, agy and Muse: vendor installers)"
gh_asset CODEX openai/codex '^codex-x86_64-unknown-linux-musl\.tar\.gz$'
gh_asset OPENCODE anomalyco/opencode '^opencode-linux-x64\.tar\.gz$'

say "# ---- D. Git"
gh_asset GH cli/cli '^gh_[0-9.]+_linux_amd64\.tar\.gz$'
gh_asset GIT_LFS git-lfs/git-lfs '^git-lfs-linux-amd64-v[0-9.]+\.tar\.gz$'
gh_asset LAZYGIT jesseduffield/lazygit '^lazygit_[0-9.]+_linux_x86_64\.tar\.gz$'
gh_asset DELTA dandavison/delta '^delta-[0-9.]+-x86_64-unknown-linux-musl\.tar\.gz$'
gh_asset GITLEAKS gitleaks/gitleaks '^gitleaks_[0-9.]+_linux_x64\.tar\.gz$'

say "# ---- E. Command-line tools"
gh_asset JQ jqlang/jq '^jq-linux-amd64$' | sed -E 's/^JQ_VERSION="jq-/JQ_VERSION="/'
gh_asset YQ mikefarah/yq '^yq_linux_amd64$'
gh_asset RIPGREP BurntSushi/ripgrep '^ripgrep-[0-9.]+-x86_64-unknown-linux-musl\.tar\.gz$'
gh_asset FD sharkdp/fd '^fd-v[0-9.]+-x86_64-unknown-linux-musl\.tar\.gz$'
gh_asset FZF junegunn/fzf '^fzf-[0-9.]+-linux_amd64\.tar\.gz$'
gh_asset BAT sharkdp/bat '^bat-v[0-9.]+-x86_64-unknown-linux-musl\.tar\.gz$'

say "# ---- F. Languages"
if want NVM; then
nvm_tag="$(latest_tag nvm-sh/nvm)"
url_pin NVM "${nvm_tag#v}" "https://raw.githubusercontent.com/nvm-sh/nvm/$nvm_tag/install.sh"
fi
gh_asset UV astral-sh/uv '^uv-x86_64-unknown-linux-gnu\.tar\.gz$'
if want GO; then
read -r go_ver go_sha < <(curl -fsSL 'https://go.dev/dl/?mode=json' | python3 -c '
import json, sys
r = json.load(sys.stdin)[0]
f = [x for x in r["files"] if x["os"] == "linux" and x["arch"] == "amd64" and x["kind"] == "archive"][0]
print(r["version"][2:], f["sha256"])')
url_pin GO "$go_ver" "https://go.dev/dl/go${go_ver}.linux-amd64.tar.gz" "$go_sha"
fi
if want JAVA; then
# Eclipse Temurin, the newest LTS (Adoptium's API gives the SHA-256).
java_lts="$(curl -fsSL https://api.adoptium.net/v3/info/available_releases | python3 -c 'import json,sys; print(json.load(sys.stdin)["most_recent_lts"])')"
read -r java_ver java_url java_sha < <(curl -fsSL "https://api.adoptium.net/v3/assets/latest/$java_lts/hotspot?architecture=x64&image_type=jdk&os=linux&vendor=eclipse" | python3 -c '
import json, sys
a = json.load(sys.stdin)[0]
print(a["version"]["openjdk_version"].removesuffix("-LTS"), a["binary"]["package"]["link"], a["binary"]["package"]["checksum"])')
url_pin JAVA "$java_ver" "$java_url" "$java_sha"
fi
if want MAVEN; then
mvn_ver="$(curl -fsSL https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/maven-metadata.xml | grep -oE '<version>3\.[0-9]+\.[0-9]+</version>' | tail -1 | grep -oE '3\.[0-9.]+[0-9]')"
mvn_url="https://dlcdn.apache.org/maven/maven-3/${mvn_ver}/binaries/apache-maven-${mvn_ver}-bin.tar.gz"
say "MAVEN_VERSION=\"$mvn_ver\""
say "MAVEN_URL=\"$mvn_url\""
say "MAVEN_SHA512=\"$(curl -fsSL "https://downloads.apache.org/maven/maven-3/${mvn_ver}/binaries/apache-maven-${mvn_ver}-bin.tar.gz.sha512" | cut -d' ' -f1)\""
say ""
fi
if want FLUTTER; then
read -r fl_ver fl_arch fl_sha < <(curl -fsSL https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json | python3 -c '
import json, sys
d = json.load(sys.stdin)
h = d["current_release"]["stable"]
r = [x for x in d["releases"] if x["hash"] == h][0]
print(r["version"], r["archive"], r["sha256"])')
url_pin FLUTTER "$fl_ver" "https://storage.googleapis.com/flutter_infra_release/releases/$fl_arch" "$fl_sha"
fi
if want ANDROID_CMDLINE_TOOLS; then
read -r at_rev at_file < <(curl -fsSL https://dl.google.com/android/repository/repository2-3.xml | python3 -c '
import re, sys
x = sys.stdin.read()
best = None
for m in re.finditer(r"<remotePackage path=\"cmdline-tools;([0-9.]+)\">(.*?)</remotePackage>", x, re.S):
    ver, body = m.group(1), m.group(2)
    if "obsolete" in body[:200] or "-alpha" in ver or "-beta" in ver:
        continue
    f = re.search(r"<url>(commandlinetools-linux-[0-9]+_latest\.zip)</url>", body)
    if f and (best is None or [int(p) for p in ver.split(".")] > [int(p) for p in best[0].split(".")]):
        best = (ver, f.group(1))
print(*best)')
url_pin ANDROID_CMDLINE_TOOLS "$at_rev" "https://dl.google.com/android/repository/$at_file"
fi
if want RUSTUP; then
rs_ver="$(curl -fsSL https://static.rust-lang.org/rustup/release-stable.toml | sed -nE "s/^version = ['\"]([^'\"]+)['\"].*/\\1/p")"
url_pin RUSTUP "$rs_ver" "https://static.rust-lang.org/rustup/archive/$rs_ver/x86_64-unknown-linux-gnu/rustup-init" \
  "$(curl -fsSL "https://static.rust-lang.org/rustup/archive/$rs_ver/x86_64-unknown-linux-gnu/rustup-init.sha256" | cut -d' ' -f1)"
fi

if want DOTNET; then
# .NET SDK: the newest LTS channel still supported (Microsoft gives the SHA-512).
read -r dn_ver dn_url dn_sha < <(curl -fsSL https://builds.dotnet.microsoft.com/dotnet/release-metadata/releases-index.json | python3 -c '
import json, sys, urllib.request
idx = [c for c in json.load(sys.stdin)["releases-index"] if c["release-type"] == "lts" and c["support-phase"] == "active"]
ch = sorted(idx, key=lambda c: [int(x) for x in c["channel-version"].split(".")])[-1]
rel = json.load(urllib.request.urlopen(ch["releases.json"]))
sdk = rel["releases"][0]["sdk"]
f = [x for x in sdk["files"] if x["name"] == "dotnet-sdk-linux-x64.tar.gz"][0]
print(sdk["version"], f["url"], f["hash"])')
if (( CHECK )); then say "DOTNET_VERSION=\"$dn_ver\""; else
say "DOTNET_VERSION=\"$dn_ver\""; say "DOTNET_URL=\"$dn_url\""; say "DOTNET_SHA512=\"$dn_sha\""; say ""; fi
fi

say "# ---- G. Database clients"
gh_asset MONGOSH mongodb-js/mongosh '^mongosh-[0-9.]+-linux-x64\.tgz$'

say "# ---- H. Kubernetes and CI/CD"
if want KUBECTL; then
kc="$(curl -fsSL https://dl.k8s.io/release/stable.txt)"
url_pin KUBECTL "${kc#v}" "https://dl.k8s.io/release/$kc/bin/linux/amd64/kubectl" \
  "$( (( CHECK )) || curl -fsSL "https://dl.k8s.io/release/$kc/bin/linux/amd64/kubectl.sha256")"
fi
if want HELM; then
# Helm's release archives are on get.helm.sh (not on GitHub), each with its .sha256sum.
hl="$(latest_tag helm/helm)"
url_pin HELM "${hl#v}" "https://get.helm.sh/helm-$hl-linux-amd64.tar.gz" \
  "$( (( CHECK )) || curl -fsSL "https://get.helm.sh/helm-$hl-linux-amd64.tar.gz.sha256sum" | cut -d' ' -f1)"
fi
gh_asset KUBECTX ahmetb/kubectx '^kubectx_v[0-9.]+_linux_x86_64\.tar\.gz$'
gh_asset KUBENS ahmetb/kubectx '^kubens_v[0-9.]+_linux_x86_64\.tar\.gz$'
gh_asset KIND kubernetes-sigs/kind '^kind-linux-amd64$'
gh_asset K9S derailed/k9s '^k9s_Linux_amd64\.tar\.gz$'
gh_asset STERN stern/stern '^stern_[0-9.]+_linux_amd64\.tar\.gz$'
gh_asset KREW kubernetes-sigs/krew '^krew-linux_amd64\.tar\.gz$'
gh_asset CMCTL cert-manager/cmctl '^cmctl_linux_amd64\.tar\.gz$'
gh_asset ARGOCD argoproj/argo-cd '^argocd-linux-amd64$'
gh_asset TKN tektoncd/cli '^tkn_[0-9.]+_Linux_x86_64\.tar\.gz$'
gh_asset ARGO argoproj/argo-workflows '^argo-linux-amd64\.gz$'
gh_asset ARGO_ROLLOUTS argoproj/argo-rollouts '^kubectl-argo-rollouts-linux-amd64$'

say "# ---- I. Cloud"
gh_asset MKCERT FiloSottile/mkcert '^mkcert-v[0-9.]+-linux-amd64$'
# HashiCorp's release zips, checked against their SHA256SUMS.
for hc in terraform vault; do
  want "${hc^^}" || continue
  hc_ver="$(curl -fsSL "https://checkpoint-api.hashicorp.com/v1/check/$hc" | python3 -c 'import json,sys; print(json.load(sys.stdin)["current_version"])')"
  hc_zip="${hc}_${hc_ver}_linux_amd64.zip"
  url_pin "${hc^^}" "$hc_ver" "https://releases.hashicorp.com/$hc/$hc_ver/$hc_zip" \
    "$( (( CHECK )) || curl -fsSL "https://releases.hashicorp.com/$hc/$hc_ver/${hc}_${hc_ver}_SHA256SUMS" | awk -v f="$hc_zip" '$2 == f {print $1}')"
done
if want GCLOUD; then
# Google Cloud CLI: the newest version of its "rapid" channel, the Linux tarball.
gc_ver="$(curl -fsSL https://dl.google.com/dl/cloudsdk/channels/rapid/components-2.json | python3 -c 'import json,sys; print(json.load(sys.stdin)["version"])')"
url_pin GCLOUD "$gc_ver" "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-$gc_ver-linux-x86_64.tar.gz"
fi
if want AZURE_CLI; then
# Azure CLI: Microsoft's azure-cli package on PyPI, installed with uv (which
# checks the package hashes PyPI publishes), on this Python.
say "AZURE_CLI_VERSION=\"$(curl -fsSL https://pypi.org/pypi/azure-cli/json | python3 -c 'import json,sys; print(json.load(sys.stdin)["info"]["version"])')\""
(( CHECK )) || say "AZURE_CLI_PYTHON=\"3.13\""
say ""
fi
